---
driver:
  name: docker

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-7.2
    driver_config:
      image: centos:7.2
      platform: centos

suites:
  - name: zaz
    run_list:
      - recipe[foo::bar]
...
...
