---
driver:
  name: docker

provisioner:
  name: shell

platforms:
  - name: ubuntu/nginx
    driver:
      box: nginx
      provider: virtualbox
 
verifier:
  name: inspec

suites:
  - name: default
