---
driver:
  name: docker

provisioner:
  name: shell

platforms:
  - name: docker/nginx64
    driver:
      box: nginx64
      provider: ubuntu-1604
 
verifier:
  name: inspec

suites:
  - name: default
