---
driver:
  name: docker

provisioner:
  name: shell

platforms:
  - name: default-nginx
    driver:
      box: nginx:0.1
      provider: ubuntu
 
verifier:
  name: inspec

suites:
  - name: default
