---
driver:
  name: docker

provisioner:
  name: shell

platforms:
  - name: nginx
    driver:
      box: docker/nginx
      provider: virtualbox
 
verifier:
  name: inspec

suites:
  - name: default
