---
driver:
  name: docker
  use_sudo: false
  privileged: true
  run_command: /usr/sbin/init

provisioner:
  name: chef_zero

platforms:
  - name: centos
    image: centos:7

suites:
  - name: default
    run_list: []
