---
driver:
  name: docker
  use_sudo: false
  privileged: true
  run_command: /usr/sbin/init
  
provisioner:
  name: chef_zero

platforms:
  - name: nginx
    image: nginx:0.1
        
verifier:
  name: inspec

suites:
  - name: default
    run_list: []
