---
driver:
  name: docker
  use_sudo: false
  privileged: true
  run_command: /usr/sbin/init

provisioner:
  name: chef_zero

platforms:
  - name: docker/nginx
    image: nikcbg/nginx64
    
verifier:
  name: inspec

suites:
  - name: default
    run_list: []
