---
driver:
  name: docker

provisioner:
  name: shell

platforms:
  - name:docker/nginx
    driver:
      box: nginx:0.1
      provider: virtualbox
 
verifier:
  name: inspec

suites:
  - name: default
